version: '3.2'
services:
  users-service-db:
    container_name: qwitter-users-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '6001:1433'
    environment:
      SA_PASSWORD: 'qwitter_password_xyz@secure123'
      ACCEPT_EULA: 'Y'
  posts-service-db:
    container_name: qwitter-posts-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '6002:1433'
    environment:
      SA_PASSWORD: 'qwitter_password_xyz@secure123'
      ACCEPT_EULA: 'Y'
